name: 'Settings Tray'
type: module
description: 'Allows users to directly edit the configuration of blocks on the current page.'
package: Core
# version: VERSION
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual

# Information added by Drupal.org packaging script on 2022-08-17
version: '9.5.x-dev'
project: 'drupal'
datestamp: 1660735355
